package b011a3;

public class test {
    public static void main(String[] args) {
        Frau anna = new Frau("Anna Carolina zu Seidlitz-Benrath", 16, 166, 56);
        Frau britt = new Frau("Britt-Marie Hellendal", 18, 192, 76);
        Mann bernd = new Mann("Bernd Rosenberg", 54, 184, 90);
        Mann neumann = new Mann("", 0, 53, 4);
        Frau zazie = new Frau("Zazie Queneau", 67, 157, 65);
        Mensch ma = anna;
        Mensch mb = bernd;
        Mensch.anzahl();
        Frau.anzahl();
        Mann.anzahl();
        ma.anzahl();
        mb.anzahl();
        anna.anzahl();
        britt.anzahl();
        bernd.anzahl();
        neumann.anzahl();
        zazie.anzahl();
        Frau celine = new Frau("Celine Kahrenbach", 36, 179, 70);
        Mensch.anzahl();
        Frau.anzahl();
        Mann.anzahl();
        Mann detlef = new Mann("Detlef Mahr", 13, 149, 44);
        Mensch.anzahl();
        Frau.anzahl();
        Mann.anzahl();
        Frau erika = new Frau("Erika Weitermann", 49, 168, 71);
        Mensch.anzahl();
        Frau.anzahl();
        Mann.anzahl();
        ma.anzahl();
        mb.anzahl();
        anna.anzahl();
        britt.anzahl();
        bernd.anzahl();
        neumann.anzahl();
        zazie.anzahl();
        anna.name();
        britt.name();
        bernd.name();
        neumann.name();
        zazie.name();
        ma.name();
        mb.name();
        anna.chromosomen();
        britt.chromosomen();
        bernd.chromosomen();
        neumann.chromosomen();
        zazie.chromosomen();
        ma.chromosomen();
        mb.chromosomen();
        anna.alter();
        britt.alter();
        bernd.alter();
        neumann.alter();
        zazie.alter();
        ma.alter();
        mb.alter();
        ma.setAlter(17);
        mb.setAlter(55);
        anna.alter();
        bernd.alter();
        Mensch.volljaehrigkeitsAlter();
        anna.volljaehrigkeitsAlter();
        britt.volljaehrigkeitsAlter();
        bernd.volljaehrigkeitsAlter();
        neumann.volljaehrigkeitsAlter();
        zazie.volljaehrigkeitsAlter();
        ma.volljaehrigkeitsAlter();
        mb.volljaehrigkeitsAlter();
        anna.istVolljaehrig();
        britt.istVolljaehrig();
        bernd.istVolljaehrig();
        neumann.istVolljaehrig();
        zazie.istVolljaehrig();
        ma.istVolljaehrig();
        mb.istVolljaehrig();
        anna.groesse();
        britt.groesse();
        bernd.groesse();
        neumann.groesse();
        zazie.groesse();
        ma.groesse();
        mb.groesse();
        ma.setGroesse(168);
        mb.setGroesse(182);
        anna.groesse();
        bernd.groesse();
        anna.gewicht();
        britt.gewicht();
        bernd.gewicht();
        neumann.gewicht();
        zazie.gewicht();
        ma.gewicht();
        mb.gewicht();
        ma.setGewicht(58);
        mb.setGewicht(92);
        anna.gewicht();
        bernd.gewicht();
        anna.preisHaarschnitt();
        britt.preisHaarschnitt();
        bernd.preisHaarschnitt();
        neumann.preisHaarschnitt();
        zazie.preisHaarschnitt();
        ma.preisHaarschnitt();
        mb.preisHaarschnitt();
        System.out.println(anna.toString());
    }
}
